version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=marvin
      - MARIADB_PASSWORD=NsaPool42
      - MARIADB_DATABASE=back
  myapp:
    image: 'bitnami/symfony:1'
    ports:
      - '8000:8000'
    volumes:
      - '/app/back:/docker/api'
    environment:
      - SYMFONY_PROJECT_NAME=back
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=marvin
      - MARIADB_PASSWORD=NsaPool42
      - MARIADB_DATABASE=nsapool
    depends_on:
      - mariadb